# Generated by Django 5.1.4 on 2026-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoPartidaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Punto de partida', help_text='Ej: Cocina central, Depósito', max_length=200, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, default='', help_text='Dirección literal (opcional)', verbose_name='Dirección')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Coordenada del punto de partida para optimizar rutas', max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Coordenada del punto de partida para optimizar rutas', max_digits=9, verbose_name='Longitud')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el algoritmo usará este punto como origen y destino al reordenar entregas.', verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Punto de partida (entregas)',
                'verbose_name_plural': 'Puntos de partida (entregas)',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
