# Generated by Django 5.1.4 on 2026-02-05 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_factura_a_cobro'),
        ('contracts', '0009_extension_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='contracts.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='numero_cobro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de cobro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing.cobro', verbose_name='Cobro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('qr', 'QR'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='qr', max_length=20, verbose_name='Método de pago'),
        ),
    ]
