# Generated by Django 5.1.4 on 2026-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_default_metodo_pago_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Se calcula automáticamente si se deja vacío (según período, plan y frecuencia del contrato).', null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
