# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dias_vencimiento_cobro',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='Días para vencimiento del cobro',
                help_text='Días después de «período hasta» para la fecha de vencimiento del cobro. Positivo = después, negativo = antes. Si está vacío se usa la regla por frecuencia del contrato (mensual: 15, resto: 7).'
            ),
        ),
    ]
