# Generated by Django 6.0.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_dias_vencimiento_cobro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='caracteristicas',
        ),
    ]
