# Generated by Django 6.0.2 on 2026-02-05 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('frecuencia_pago', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], max_length=20, verbose_name='Frecuencia de pago')),
                ('direccion_entrega', models.JSONField(default=dict, help_text='Dirección de entrega en formato JSON', verbose_name='Dirección de entrega')),
                ('horario_entrega', models.CharField(blank=True, help_text='Ej: 08:00 - 10:00', max_length=100, null=True, verbose_name='Horario de entrega')),
                ('dias_entrega', models.JSONField(default=list, help_text='Lista de días de la semana en formato JSON', verbose_name='Días de entrega')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_pausa', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausa')),
                ('fecha_reanudacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reanudación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clients.cliente', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='plans.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
