# Generated by Django 5.1.4 on 2026-02-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PausaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio pausa')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin pausa')),
                ('motivo', models.CharField(blank=True, help_text='Ej: vacaciones, viaje, etc.', max_length=255, null=True, verbose_name='Motivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='contracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pausa de contrato',
                'verbose_name_plural': 'Pausas de contrato',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
