# Generated by Django 5.1.4 on 2026-02-05 02:16

from django.db import migrations, models


def json_direccion_a_texto(apps, schema_editor):
    """Convierte direccion_entrega JSON existente a texto legible."""
    Contrato = apps.get_model('contracts', 'Contrato')
    for c in Contrato.objects.all():
        # En este punto el modelo histórico aún tiene direccion_entrega (JSON)
        d = c.direccion_entrega
        if not d:
            continue
        if isinstance(d, dict):
            partes = []
            for key in ('calle', 'numero', 'colonia', 'ciudad', 'codigo_postal', 'referencia'):
                val = d.get(key)
                if val:
                    if key == 'numero':
                        partes.append(f"#{val}")
                    elif key == 'codigo_postal':
                        partes.append(f"C.P. {val}")
                    else:
                        partes.append(str(val))
            texto = ', '.join(partes) if partes else str(d)
        else:
            texto = str(d)
        Contrato.objects.filter(pk=c.pk).update(direccion_entrega_new=texto)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_pausa_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='link_maps',
            field=models.URLField(blank=True, help_text='URL de Google Maps con la ubicación (opcional)', max_length=500, null=True, verbose_name='Enlace Google Maps'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dias_entrega',
            field=models.JSONField(default=list, help_text='Días de la semana en que se entrega el servicio (lunes, martes, …)', verbose_name='Días de entrega'),
        ),
        # Paso 1: añadir campo texto temporal
        migrations.AddField(
            model_name='contrato',
            name='direccion_entrega_new',
            field=models.TextField(blank=True, default='', help_text='Dirección completa donde se entrega el servicio', verbose_name='Dirección de entrega'),
        ),
        # Paso 2: copiar datos JSON a texto
        migrations.RunPython(json_direccion_a_texto, noop),
        # Paso 3: quitar campo antiguo
        migrations.RemoveField(model_name='contrato', name='direccion_entrega'),
        # Paso 4: renombrar nuevo a direccion_entrega
        migrations.RenameField(
            model_name='contrato',
            old_name='direccion_entrega_new',
            new_name='direccion_entrega',
        ),
    ]
