# Generated by Django 5.1.4 on 2026-02-05 03:16

from django.db import migrations, models


def parse_horario_to_time(apps, schema_editor):
    """Convierte horario_entrega (CharField) a time para el nuevo campo."""
    Contrato = apps.get_model('contracts', 'Contrato')
    for c in Contrato.objects.exclude(horario_entrega_old__isnull=True).exclude(horario_entrega_old=''):
        val = c.horario_entrega_old.strip()
        # Tomar primera parte si es "08:00 - 10:00" o "08:00"
        if ' - ' in val:
            val = val.split(' - ')[0].strip()
        if ':' in val:
            parts = val.split(':')
            try:
                h = int(parts[0].strip())
                m = int(parts[1].strip()[:2]) if len(parts) > 1 else 0
                if 0 <= h <= 23 and 0 <= m <= 59:
                    from datetime import time
                    c.horario_entrega = time(h, m)
                    c.save(update_fields=['horario_entrega'])
            except (ValueError, IndexError):
                pass


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_direccion_texto_y_link_maps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='horario_entrega',
            new_name='horario_entrega_old',
        ),
        migrations.AddField(
            model_name='contrato',
            name='horario_entrega',
            field=models.TimeField(blank=True, help_text='Hora de entrega (ej. 08:30)', null=True, verbose_name='Horario de entrega'),
        ),
        migrations.RunPython(parse_horario_to_time, noop_reverse),
        migrations.RemoveField(
            model_name='contrato',
            name='horario_entrega_old',
        ),
    ]
