# Generated by Django 5.1.4 on 2026-02-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_horario_entrega_timefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='notas_entregador',
            field=models.TextField(blank=True, help_text='Indicaciones opcionales para quien realiza la entrega (ej. timbre, dejar en conserjería)', null=True, verbose_name='Notas para el entregador'),
        ),
    ]
