# Generated by Django 5.1.4 on 2026-02-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_add_notas_entregador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='frecuencia_pago',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=20, verbose_name='Frecuencia de pago'),
        ),
    ]
