# Generated by Django 5.1.4 on 2026-02-05 06:02

from django.db import migrations, models
from django.utils import timezone


def set_fecha_cancelacion_from_estado(apps, schema_editor):
    """Copia estado='cancelado' a fecha_cancelacion antes de eliminar el campo estado."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE contracts_contrato
            SET fecha_cancelacion = COALESCE(fecha_actualizacion, %s)
            WHERE estado = %s
            """,
            [timezone.now(), 'cancelado'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_frecuencia_pago_default_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Si está definida, el contrato está cancelado.', null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.RunPython(set_fecha_cancelacion_from_estado, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contrato',
            name='estado',
        ),
    ]
