# Generated by Django 5.1.4 on 2026-02-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_actualizar_fecha_fin_desde_cobros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionVigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_extension', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de extensión')),
                ('dias_agregados', models.PositiveIntegerField(help_text='Número de días extra de catering.', verbose_name='Días agregados')),
                ('motivo', models.CharField(help_text='Razón de la extensión (ej. cortesía, compensación, etc.).', max_length=255, verbose_name='Motivo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensiones_vigencia', to='contracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Extensión de vigencia',
                'verbose_name_plural': 'Extensiones de vigencia',
                'ordering': ['-fecha_extension'],
            },
        ),
    ]
