# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_extension_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='no_incluye_delivery',
            field=models.BooleanField(
                default=False,
                verbose_name='No incluye delivery',
                help_text='Si está marcado, este contrato no incluye servicio de entrega a domicilio.'
            ),
        ),
    ]
