# Generated by Django 5.1.4 on 2026-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contrato_no_incluye_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para optimizar el orden de entrega en la ruta (Google Maps)', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para optimizar el orden de entrega en la ruta (Google Maps)', max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
