# Generated by Django 5.1.4 on 2026-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_add_coordenadas_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='extensionvigencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='extensionvigencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='pausacontrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='pausacontrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
    ]
