# Generated by Django 4.2.30 on 2026-06-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_puntoentrega'),
        ('contracts', '0012_add_created_at_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='punto_entrega',
            field=models.ForeignKey(blank=True, help_text='Edificio, condominio u oficina donde se agrupan varias entregas en la misma ubicación física.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='routes.puntoentrega', verbose_name='Punto de entrega'),
        ),
    ]
