# Generated by Django 6.0.2 on 2026-02-05 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('vehiculo', models.CharField(blank=True, help_text='Tipo de vehículo utilizado para entregas', max_length=100, null=True, verbose_name='Vehículo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la ruta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='routes.entregador', verbose_name='Entregador')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-fecha', 'entregador'],
            },
        ),
        migrations.CreateModel(
            name='RutaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_entrega', models.PositiveIntegerField(help_text='Orden en que se realizará la entrega en esta ruta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden de entrega')),
                ('direccion_entrega', models.JSONField(default=dict, help_text='Dirección específica para esta entrega en formato JSON', verbose_name='Dirección de entrega')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_rutas', to='contracts.contrato', verbose_name='Contrato')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_clientes', to='routes.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Cliente de Ruta',
                'verbose_name_plural': 'Clientes de Rutas',
                'ordering': ['ruta', 'orden_entrega'],
                'unique_together': {('ruta', 'contrato')},
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='clientes',
            field=models.ManyToManyField(related_name='rutas', through='routes.RutaCliente', to='contracts.contrato', verbose_name='Clientes'),
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('fecha', 'entregador')},
        ),
    ]
