# Generated by Django 5.1.4 on 2026-02-05 03:19

import uuid
from django.db import migrations, models


def generar_codigos_entrega(apps, schema_editor):
    """Asigna un código único a cada RutaCliente existente."""
    RutaCliente = apps.get_model('routes', 'RutaCliente')
    usados = set()
    for rc in RutaCliente.objects.all():
        for _ in range(20):
            codigo = uuid.uuid4().hex[:10].upper()
            if codigo not in usados:
                usados.add(codigo)
                rc.codigo_entrega = codigo
                rc.save(update_fields=['codigo_entrega'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutacliente',
            name='codigo_entrega',
            field=models.CharField(blank=True, default='', help_text='Identificador único de esta entrega (ruta imprimible y reporte cocina)', max_length=20, verbose_name='Código de entrega'),
        ),
        migrations.RunPython(generar_codigos_entrega, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rutacliente',
            name='codigo_entrega',
            field=models.CharField(blank=True, help_text='Identificador único de esta entrega (ruta imprimible y reporte cocina)', max_length=20, unique=True, verbose_name='Código de entrega'),
        ),
    ]
