# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_add_codigo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='duracion_legs_segundos',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de duraciones en segundos por tramo (desde API Directions); se usa para tiempo estimado de llegada.',
                verbose_name='Duración por tramo (seg)',
            ),
        ),
    ]
