# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_ruta_duracion_legs_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutacliente',
            name='entregada',
            field=models.BooleanField(default=False, help_text='Marcado cuando se confirma la entrega en esta parada', verbose_name='Entregada'),
        ),
        migrations.AddField(
            model_name='rutacliente',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Momento en que se marcó como entregada', null=True, verbose_name='Fecha/hora entrega'),
        ),
    ]
