# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_rutacliente_entregada_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutacliente',
            name='no_entregada',
            field=models.BooleanField(default=False, help_text='Marcado cuando se reporta que no se pudo realizar la entrega', verbose_name='No entregada'),
        ),
        migrations.AddField(
            model_name='rutacliente',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, default='', help_text='Descripción obligatoria del motivo cuando no se pudo entregar', verbose_name='Motivo no entrega'),
        ),
    ]
