# Generated by Django 5.1.4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0005_rutacliente_no_entregada_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutacliente',
            name='marcadopor_entregada',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario que marcó esta parada como entregada',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rutas_marcadas_entregada',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Marcado entregada por',
            ),
        ),
        migrations.AddField(
            model_name='rutacliente',
            name='fecha_no_entrega',
            field=models.DateTimeField(
                blank=True,
                help_text='Momento en que se reportó que no se pudo entregar',
                null=True,
                verbose_name='Fecha/hora reporte no entrega',
            ),
        ),
        migrations.AddField(
            model_name='rutacliente',
            name='marcadopor_no_entrega',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario que reportó que no se pudo entregar',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rutas_marcadas_no_entregada',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Reportado no entrega por',
            ),
        ),
    ]
