# Generated by Django 6.0.2 on 2026-02-09 15:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_created_at_updated_at'),
        ('routes', '0007_add_created_at_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entregador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_ruta', to='routes.entregador', verbose_name='Entregador')),
            ],
            options={
                'verbose_name': 'Plantilla de ruta',
                'verbose_name_plural': 'Plantillas de ruta',
                'ordering': ['entregador__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntregaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('entregada', models.BooleanField(default=False, verbose_name='Entregada')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora entrega')),
                ('no_entregada', models.BooleanField(default=False, verbose_name='No entregada')),
                ('motivo_no_entrega', models.TextField(blank=True, default='', verbose_name='Motivo no entrega')),
                ('fecha_no_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora reporte no entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_dia', to='contracts.contrato', verbose_name='Contrato')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_dia', to='routes.entregador', verbose_name='Entregador')),
                ('marcadopor_entregada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_dia_marcadas', to=settings.AUTH_USER_MODEL, verbose_name='Marcado entregada por')),
                ('marcadopor_no_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_dia_no_entregada', to=settings.AUTH_USER_MODEL, verbose_name='Reportado no entrega por')),
            ],
            options={
                'verbose_name': 'Entrega del día',
                'verbose_name_plural': 'Entregas del día',
                'ordering': ['fecha', 'entregador', 'contrato'],
                'unique_together': {('entregador', 'contrato', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaRutaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_entrega', models.CharField(blank=True, help_text='Identificador único corto para esta parada', max_length=20, unique=True, verbose_name='Código de entrega')),
                ('orden_entrega', models.PositiveIntegerField(help_text='Orden en que se realizará la entrega (mismo orden todos los días en que aplique)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_rutas', to='contracts.contrato', verbose_name='Contrato')),
                ('plantilla_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='routes.plantillaruta', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Cliente en plantilla',
                'verbose_name_plural': 'Clientes en plantilla',
                'ordering': ['plantilla_ruta', 'orden_entrega'],
                'unique_together': {('plantilla_ruta', 'contrato')},
            },
        ),
    ]
