# Generated by Django 6.0.2 on 2026-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_migrate_ruta_to_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaruta',
            name='duracion_legs_segundos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de duraciones en segundos por tramo (desde API Directions).', verbose_name='Duración por tramo (seg)'),
        ),
    ]
