# Generated by Django 6.0.2 on 2026-02-10 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_created_at_updated_at'),
        ('planning', '0009_planificacionmenu_fecha_plan_unique_together'),
        ('routes', '0010_plantilla_duracion_legs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAsignacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_asignaciones_entrega', to='contracts.contrato', verbose_name='Contrato')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_asignaciones_entrega', to='routes.entregador', verbose_name='Entregador')),
                ('planificacion_menu', models.ForeignKey(blank=True, help_text='Menú planificado para esa fecha y plan del contrato; null si no había menú.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_asignaciones_entrega', to='planning.planificacionmenu', verbose_name='Planificación menú (dieta del día)')),
            ],
            options={
                'verbose_name': 'Histórico asignación entrega',
                'verbose_name_plural': 'Histórico asignaciones entrega',
                'ordering': ['-fecha', 'entregador', 'contrato'],
                'unique_together': {('fecha', 'contrato')},
            },
        ),
    ]
