# Generated by Django 6.0.2 on 2026-02-10 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_historico_asignacion_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario que inicia sesión como este entregador (solo ve sus rutas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregador_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado'),
        ),
    ]
