# Generated by Django 4.2.30 on 2026-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_add_entregador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='checkin_auto',
            field=models.BooleanField(blank=True, help_text='Vacío = usar el valor del sistema. Marca la llegada automáticamente al entrar en el radio.', null=True, verbose_name='Check-in automático por GPS'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='checkin_radio_metros',
            field=models.PositiveIntegerField(blank=True, help_text='Vacío = usar el valor del sistema. Distancia para considerar que llegó a la parada.', null=True, verbose_name='Radio de aproximación (m)'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='ping_intervalo_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Vacío = usar el valor del sistema. Cada cuántos segundos la app envía su ubicación.', null=True, verbose_name='Intervalo de envío GPS (s)'),
        ),
    ]
