# Generated by Django 4.2.30 on 2026-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_entregador_checkin_auto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('notas_acceso', models.TextField(blank=True, help_text='Portero, citófono, piso, código de acceso, etc.', verbose_name='Notas de acceso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Punto de entrega',
                'verbose_name_plural': 'Puntos de entrega',
                'ordering': ['nombre'],
            },
        ),
    ]
