# Generated by Django 6.0.2 on 2026-02-05 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Previsión de Compra',
                'verbose_name_plural': 'Previsiones de Compra',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='PrevisionCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad total')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsiones', to='recipes.ingrediente', verbose_name='Ingrediente')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.previsioncompra', verbose_name='Previsión')),
            ],
            options={
                'verbose_name': 'Item de Previsión de Compra',
                'verbose_name_plural': 'Items de Previsiones de Compra',
                'ordering': ['prevision', 'ingrediente'],
                'unique_together': {('prevision', 'ingrediente', 'unidad_medida')},
            },
        ),
    ]
