# Generated by Django 6.0.2 on 2026-02-05 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direcciones', models.JSONField(default=list, help_text='Lista de direcciones del cliente en formato JSON', verbose_name='Direcciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteNoGustado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('motivo', models.TextField(blank=True, help_text='Razón por la que no le gusta este ingrediente', null=True, verbose_name='Motivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_no_gustados', to='clients.cliente', verbose_name='Cliente')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_que_no_gustan', to='recipes.ingrediente', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente No Gustado',
                'verbose_name_plural': 'Ingredientes No Gustados',
                'ordering': ['cliente', 'ingrediente'],
                'unique_together': {('cliente', 'ingrediente')},
            },
        ),
    ]
