# Generated by Django 5.1.4 on 2026-02-05 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_direccion_y_link_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='titular',
            field=models.ForeignKey(blank=True, help_text='Si este cliente es dependiente de otro (ej. familiar), indique el cliente titular para cobranzas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='clients.cliente', verbose_name='Cliente titular'),
        ),
    ]
