# Generated by Django 5.1.4 on 2026-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_titular_dependientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para mapas y optimización de rutas (Google Maps)', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para mapas y optimización de rutas (Google Maps)', max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
