# Generated by Django 5.1.4 on 2026-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_coordenadas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='ingredientenogustado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='ingredientenogustado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
    ]
