# Generated by Django 6.0.2 on 2026-02-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('recetas_alternativas', models.JSONField(blank=True, default=list, help_text='Lista de IDs de recetas alternativas sugeridas por el sistema', verbose_name='Recetas alternativas sugeridas')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='contracts.contrato', verbose_name='Contrato')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones', to='diets.dieta', verbose_name='Dieta')),
            ],
            options={
                'verbose_name': 'Planificación de Dieta',
                'verbose_name_plural': 'Planificaciones de Dietas',
                'ordering': ['fecha', 'contrato'],
                'unique_together': {('fecha', 'contrato')},
            },
        ),
    ]
