# Generated by Django 5.1.4 on 2026-02-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_tipo_comida_required'),
        ('planning', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionRecetaSustituta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones', to='planning.planificaciondieta', verbose_name='Planificación')),
                ('receta_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustituciones_como_original', to='recipes.receta', verbose_name='Receta original')),
                ('receta_sustituta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustituciones_como_sustituta', to='recipes.receta', verbose_name='Receta sustituta')),
                ('tipo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustituciones_planificacion', to='diets.tipocomida', verbose_name='Momento / Tipo de comida')),
            ],
            options={
                'verbose_name': 'Sustitución de receta',
                'verbose_name_plural': 'Sustituciones de recetas',
                'ordering': ['planificacion', 'tipo_comida'],
                'unique_together': {('planificacion', 'tipo_comida', 'receta_original')},
            },
        ),
    ]
