# Generated by Django 5.1.4 on 2026-02-05 01:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('diets', '0004_dieta_planes_m2m'),
        ('planning', '0002_planificacion_receta_sustituta'),
        ('plans', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_menu', to='plans.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Planificación menú (fecha + plan)',
                'verbose_name_plural': 'Planificaciones menú',
                'ordering': ['-fecha', 'plan'],
                'unique_together': {('fecha', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='PlanificacionClienteSustituta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones_planificacion', to='contracts.contrato', verbose_name='Contrato')),
                ('receta_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustituciones_cliente_original', to='recipes.receta', verbose_name='Receta original')),
                ('receta_sustituta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustituciones_cliente_sustituta', to='recipes.receta', verbose_name='Receta sustituta')),
                ('tipo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustituciones_cliente', to='diets.tipocomida', verbose_name='Momento del día')),
            ],
            options={
                'verbose_name': 'Sustitución por cliente (fecha)',
                'verbose_name_plural': 'Sustituciones por cliente',
                'ordering': ['fecha', 'contrato', 'tipo_comida'],
                'unique_together': {('fecha', 'contrato', 'tipo_comida', 'receta_original')},
            },
        ),
        migrations.CreateModel(
            name='PlanificacionMenuReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('planificacion_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='planning.planificacionmenu', verbose_name='Planificación menú')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_menu_receta', to='recipes.receta', verbose_name='Receta')),
                ('tipo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_menu_receta', to='diets.tipocomida', verbose_name='Momento del día')),
            ],
            options={
                'verbose_name': 'Receta del menú planificado',
                'verbose_name_plural': 'Recetas del menú planificado',
                'ordering': ['planificacion_menu', 'tipo_comida', 'orden'],
                'unique_together': {('planificacion_menu', 'tipo_comida', 'receta')},
            },
        ),
    ]
