# Generated by Django 6.0.2 on 2026-02-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_created_at_updated_at'),
        ('diets', '0005_add_created_at_updated_at'),
        ('planning', '0004_add_created_at_updated_at'),
        ('recipes', '0013_add_created_at_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionClienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_personalizadas', to='contracts.contrato', verbose_name='Contrato')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dietas_personalizadas', to='recipes.receta', verbose_name='Receta')),
                ('tipo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dietas_personalizadas', to='diets.tipocomida', verbose_name='Momento del día')),
            ],
            options={
                'verbose_name': 'Dieta personalizada (cliente + fecha + momento)',
                'verbose_name_plural': 'Dietas personalizadas',
                'ordering': ['fecha', 'contrato', 'tipo_comida'],
                'unique_together': {('fecha', 'contrato', 'tipo_comida')},
            },
        ),
    ]
