# Generated by Django 6.0.2 on 2026-02-10 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_created_at_updated_at'),
        ('diets', '0005_add_created_at_updated_at'),
        ('planning', '0005_add_planificacion_cliente_receta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionclientereceta',
            options={'ordering': ['fecha', 'contrato', 'tipo_comida', 'orden'], 'verbose_name': 'Dieta personalizada (cliente + fecha + momento)', 'verbose_name_plural': 'Dietas personalizadas'},
        ),
        migrations.AlterUniqueTogether(
            name='planificacionclientereceta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planificacionclientereceta',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden de la receta dentro del mismo momento (1 = primera, 2 = segunda, …)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden'),
        ),
        migrations.AlterUniqueTogether(
            name='planificacionclientereceta',
            unique_together={('fecha', 'contrato', 'tipo_comida', 'orden')},
        ),
    ]
