# Generated by Django 6.0.2 on 2026-02-10 00:18

from django.db import migrations, models


def eliminar_duplicados_fecha(apps, schema_editor):
    """Deja una sola planificación por fecha (la de menor pk); elimina el resto."""
    PlanificacionMenu = apps.get_model('planning', 'PlanificacionMenu')
    from django.db.models import Min
    duplicadas = (
        PlanificacionMenu.objects.values('fecha')
        .annotate(min_id=Min('id'))
        .values_list('fecha', 'min_id')
    )
    for fecha, id_a_mantener in duplicadas:
        PlanificacionMenu.objects.filter(fecha=fecha).exclude(pk=id_a_mantener).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_planificacion_cliente_receta_orden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificacionmenu',
            unique_together=set(),
        ),
        migrations.RunPython(eliminar_duplicados_fecha, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='planificacionmenu',
            name='fecha',
            field=models.DateField(unique=True, verbose_name='Fecha'),
        ),
    ]
    # Permitir que PostgreSQL aplique el ALTER en una transacción limpia
    atomic = False
