# Generated by Django 6.0.2 on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_unique_fecha_planificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionclientereceta',
            name='receta_original',
            field=models.ForeignKey(
                blank=True,
                help_text='Plato del menú del plan que se sustituye',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='dietas_personalizadas_reemplazando',
                to='recipes.receta',
                verbose_name='Reemplaza (plato del menú)'
            ),
        ),
    ]
