# Generated by Django 6.0.2 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_planificacion_clientereceta_receta_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionmenu',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='planificacionmenu',
            unique_together={('fecha', 'plan')},
        ),
    ]
