"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables desde .env (proyecto raíz, donde está manage.py)
from dotenv import load_dotenv
load_dotenv(BASE_DIR.parent / '.env')

# OpenAI - clave desde variable de entorno o .env (obligatoria para sugerir menús con IA)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Google Maps API - para optimizar orden de entregas en rutas (Directions API, servidor).
# Esta clave NO debe tener restricción por HTTP referrer (solo aplica a peticiones desde navegador).
# Usar "Ninguna" o "Direcciones IP" en restricciones de aplicación en Google Cloud Console.
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Google Maps JS API (frontend). Idealmente usar una key con restricción por HTTP referrer.
# Si no se define, se reutiliza GOOGLE_MAPS_API_KEY.
GOOGLE_MAPS_BROWSER_API_KEY = os.environ.get('GOOGLE_MAPS_BROWSER_API_KEY', '') or GOOGLE_MAPS_API_KEY


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ij4jwptn39ngg$i*wrclx2*g*ri9kfww^#jx_c3^p_jko-4^#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'base',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps del sistema de catering
    'clients',
    'contracts',
    'plans',
    'recipes',
    'diets',
    'routes',
    'routing',
    'planning',
    'purchases',
    'kitchen',
    'delivery',
    'deliveries',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'base.middleware.ProfileAccessMiddleware',
    'base.middleware.AITokenUsageMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.catering_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# La configuración específica de base de datos se define en development.py, production.py, etc.
DATABASES = {}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Idioma y zona horaria (configurables por empresa vía variables de entorno)
LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'es')

TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Mexico_City')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Nombre del catering (configurable por empresa vía variable de entorno)
CATERING_NAME = os.environ.get('CATERING_NAME', 'Catering')

# Colores de marca (configurables por empresa; los tonos derivados se calculan en CSS).
# Estos son solo el tema por defecto y pueden sobreescribirse con variables de entorno.
BRAND_COLOR = os.environ.get('BRAND_COLOR', '#7CB342')
BRAND_COLOR_HOVER = os.environ.get('BRAND_COLOR_HOVER', '#689F38')

# Paleta de colores para gráficas. La primera entrada es el color de marca y el
# resto son colores categóricos distinguibles entre sí (una serie por plan, etc.).
# Configurable vía la variable de entorno CHART_PALETTE (colores separados por comas).
CHART_PALETTE = [c.strip() for c in os.environ.get('CHART_PALETTE', '').split(',') if c.strip()] or [
    BRAND_COLOR, '#1565c0', '#ff9800', '#9c27b0', '#00acc1',
    '#5d4037', '#e91e63', '#673ab7', '#00bcd4',
]
# Color para las líneas/series de totales o agregados en gráficas.
CHART_TOTAL_COLOR = os.environ.get('CHART_TOTAL_COLOR', '#37474f')

# Autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# REST Framework and API
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}
SPECTACULAR_SETTINGS = {
    'TITLE': 'Catering API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
SIMPLE_JWT = {
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Sentry: monitoreo de errores (solo si SENTRY_DSN está definido en el entorno)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from django.core.exceptions import DisallowedHost

    def _sentry_before_send(event, hint):
        exc_info = hint.get('exc_info')
        if exc_info and len(exc_info) >= 2 and isinstance(exc_info[1], DisallowedHost):
            return None
        return event

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=os.environ.get('DJANGO_ENV', 'development'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=os.environ.get('SENTRY_SEND_DEFAULT_PII', 'false').lower() in ('true', '1', 'yes'),
        before_send=_sentry_before_send,
    )
