# Generated by Django 6.0.2 on 2026-02-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas para el cocinero')),
            ],
            options={
                'verbose_name': 'Detalle de Cocina',
                'verbose_name_plural': 'Detalles de Cocina',
                'ordering': ['-fecha'],
            },
        ),
    ]
