# Generated by Django 5.1.4 on 2026-02-05 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accion', models.CharField(choices=[('estimar_nutricion_ingrediente', 'Estimar nutrición ingrediente'), ('estimar_nutricion_receta', 'Estimar nutrición receta'), ('sugerir_descripcion_receta', 'Sugerir descripción receta'), ('sugerir_ingredientes_receta', 'Sugerir ingredientes receta'), ('sugerir_dieta', 'Sugerir dieta personalizada'), ('sugerir_menu', 'Sugerir menú')], db_index=True, max_length=50)),
                ('modelo', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('exito', models.BooleanField(default=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=32)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de solicitud IA',
                'verbose_name_plural': 'Logs de solicitudes IA',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
