# Generated by Django 5.1.4 on 2026-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_ai_request_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='accion',
            field=models.CharField(choices=[('estimar_nutricion_ingrediente', 'Estimar nutrición ingrediente'), ('estimar_nutricion_receta', 'Estimar nutrición receta'), ('sugerir_descripcion_receta', 'Sugerir descripción receta'), ('sugerir_ingredientes_receta', 'Sugerir ingredientes receta'), ('sugerir_dieta', 'Sugerir dieta personalizada'), ('sugerir_menu', 'Sugerir menú'), ('importar_receta', 'Importar receta desde texto')], db_index=True, max_length=50),
        ),
    ]
