# Generated by Django 5.1.4 on 2026-02-06 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_feriado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api', models.CharField(choices=[('google_directions', 'Google Directions API'), ('google_geocoding', 'Google Geocoding API'), ('google_places', 'Google Places API')], db_index=True, max_length=32)),
                ('endpoint', models.CharField(blank=True, help_text='URL base del endpoint (sin query)', max_length=512)),
                ('request_params', models.JSONField(blank=True, default=dict, help_text='Parámetros enviados (key enmascarada)')),
                ('request_extra', models.TextField(blank=True, help_text='Otros datos del request (ej. waypoints count)')),
                ('response_status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('response_body', models.JSONField(blank=True, default=dict, help_text='Resumen o fragmento de la respuesta')),
                ('exito', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_tipo', models.CharField(blank=True, db_index=True, max_length=32)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de solicitud API externa',
                'verbose_name_plural': 'Logs de solicitudes API externas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
