# Generated by Django 5.1.4 on 2026-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_add_external_api_request_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador único del parámetro (ej. nombre_empresa, dias_aviso_vencimiento)', max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(blank=True, default='', help_text='Valor del parámetro (texto o número)', verbose_name='Valor')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción opcional para saber para qué sirve', max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Parámetro del sistema',
                'verbose_name_plural': 'Parámetros del sistema',
                'ordering': ['clave'],
            },
        ),
    ]
