# Generated by Django 6.0.2 on 2026-02-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_add_created_at_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], db_index=True, max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(db_index=True, max_length=64, verbose_name='Tipo de registro')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=255, verbose_name='Descripción del objeto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('cambios', models.JSONField(blank=True, default=list, verbose_name='Cambios realizados')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acción de usuario',
                'verbose_name_plural': 'Historial de acciones de usuarios',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
