# Generated by Django 6.0.2 on 2026-02-06 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_add_created_at_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_whatsapp', models.CharField(help_text='Número desde el que se envió el mensaje (con código de país si aplica).', max_length=30, verbose_name='Teléfono WhatsApp')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('mensaje_id_whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID mensaje WhatsApp')),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo'), ('consulta', 'Consulta'), ('otro', 'Otro')], default='reclamo', max_length=20, verbose_name='Tipo')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas internas')),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha recibido')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_whatsapp', to='clients.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reclamo / consulta WhatsApp',
                'verbose_name_plural': 'Reclamos / consultas WhatsApp',
                'ordering': ['-fecha_recibido'],
            },
        ),
    ]
