# Generated by Django 5.1.4 on 2026-02-05 02:02

import django.core.validators
from django.db import migrations, models


def noop(apps, schema_editor):
    """Sin datos ficticios: los tipos de receta se crean desde la app."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_dieta_planes_m2m'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden para mostrar en listas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de receta',
                'verbose_name_plural': 'Tipos de receta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['nombre'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='receta',
            name='momentos_dia',
            field=models.ManyToManyField(blank=True, help_text='En qué momentos del día se puede usar esta receta: Desayuno, Media mañana, Comida, Merienda, Cena (selección múltiple)', related_name='recetas_momento', to='diets.tipocomida', verbose_name='Momentos del día'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(help_text='Ingredientes y cantidades (selección múltiple con cantidad y unidad)', related_name='recetas', through='recipes.RecetaIngrediente', to='recipes.ingrediente', verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tipos_receta',
            field=models.ManyToManyField(blank=True, help_text='Ej: Comida, Masa, Postre, Complemento, Bebida, Fruta (selección múltiple)', related_name='recetas', to='recipes.tiporeceta', verbose_name='Tipo de receta'),
        ),
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
