# Generated by Django 5.1.4 on 2026-02-05 02:22
# Multi-step migration to convert unidad_medida from CharField to FK(UnidadMedida)

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def crear_unidades_y_migrar_ingredientes(apps, schema_editor):
    """Crea UnidadMedida solo a partir de valores existentes en Ingrediente y asigna FK. Sin datos ficticios."""
    UnidadMedida = apps.get_model('recipes', 'UnidadMedida')
    Ingrediente = apps.get_model('recipes', 'Ingrediente')
    valores = list(Ingrediente.objects.values_list('unidad_medida_old', flat=True).distinct())
    for nombre_str in valores:
        if nombre_str:
            UnidadMedida.objects.get_or_create(nombre=nombre_str, defaults={'orden': 99})
    for ing in Ingrediente.objects.all():
        if ing.unidad_medida_old:
            um = UnidadMedida.objects.filter(nombre=ing.unidad_medida_old).first()
            if um:
                ing.unidad_medida_id = um.id
                ing.save(update_fields=['unidad_medida_id'])


def migrar_receta_ingredientes(apps, schema_editor):
    """Crea UnidadMedida solo a partir de valores existentes en RecetaIngrediente y asigna FK. Sin datos ficticios."""
    UnidadMedida = apps.get_model('recipes', 'UnidadMedida')
    RecetaIngrediente = apps.get_model('recipes', 'RecetaIngrediente')
    for ri in RecetaIngrediente.objects.all():
        if ri.unidad_medida_old:
            um, _ = UnidadMedida.objects.get_or_create(
                nombre=ri.unidad_medida_old,
                defaults={'orden': 99}
            )
            ri.unidad_medida_id = um.id
            ri.save(update_fields=['unidad_medida_id'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_tipo_receta_y_momentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(blank=True, help_text='Opcional: ej. kg, g, L', max_length=20, null=True, verbose_name='Símbolo')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden para mostrar en listas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['orden', 'nombre'],
            },
        ),
        # Ingrediente: renombrar CharField, añadir FK, migrar, quitar CharField
        migrations.RenameField(
            model_name='ingrediente',
            old_name='unidad_medida',
            new_name='unidad_medida_old',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Unidad por defecto para este ingrediente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='recipes.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.RunPython(crear_unidades_y_migrar_ingredientes, noop),
        migrations.RemoveField(model_name='ingrediente', name='unidad_medida_old'),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Unidad por defecto para este ingrediente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='recipes.unidadmedida', verbose_name='Unidad de medida'),
        ),
        # RecetaIngrediente: igual
        migrations.RenameField(
            model_name='recetaingrediente',
            old_name='unidad_medida',
            new_name='unidad_medida_old',
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Unidad para esta cantidad en la receta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receta_ingredientes', to='recipes.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.RunPython(migrar_receta_ingredientes, noop),
        migrations.RemoveField(model_name='recetaingrediente', name='unidad_medida_old'),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Unidad para esta cantidad en la receta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receta_ingredientes', to='recipes.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
