# Generated by Django 5.1.4
# Los datos de prueba (50 recetas bebidas/postres/frutas) ya no se cargan aquí.
# Se cargan bajo demanda con: python manage.py cargar_datos_prueba

from django.db import migrations


def noop(apps, schema_editor):
    """No-op: los datos de prueba se cargan solo con el comando cargar_datos_prueba."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_unidad_medida_parametrizable'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
