# Generated by Django 5.1.4 on 2026-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recetas_bebidas_postres_frutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='info_nutricional',
            field=models.JSONField(blank=True, default=dict, help_text='Por 100g en formato JSON: {"por_100g": {"calorias": 165, "proteinas": 31, "carbohidratos": 0, "grasas": 3.6, "fibra": 0}}. Opcional: "gramos_por_unidad" para ingredientes vendidos por unidad.', verbose_name='Información nutricional'),
        ),
    ]
