# Generated by Django 5.1.4 on 2026-02-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_ingrediente_info_nutricional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='alergenos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de alérgenos que puede contener (gluten, lactosa, frutos secos, etc.)', verbose_name='Alérgenos'),
        ),
    ]
