# Generated by Django 5.1.4 on 2026-02-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_add_ingrediente_alergenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='producido_en_cocina',
            field=models.BooleanField(default=True, help_text='Si está marcado, la receta se incluye en el Resumen — Cantidades por comida del detalle de cocina.', verbose_name='Es producido en cocina'),
        ),
    ]
