# Generated by Django 5.1.4 on 2026-02-05 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_producido_en_cocina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden para mostrar en listas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Alérgeno',
                'verbose_name_plural': 'Alérgenos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
