# Generated by Django 5.1.4 on 2026-02-05 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_seed_alergenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='equivalencia_por_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cuando la unidad es 'Unidad', indique cuántos gramos o ml tiene cada unidad (ej. 1 huevo = 50 g).", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Equivalencia por unidad'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='equivalencia_por_unidad_tipo',
            field=models.CharField(blank=True, choices=[('g', 'Gramos'), ('ml', 'Mililitros')], default='g', help_text='Si la equivalencia anterior es en gramos o en mililitros.', max_length=5, verbose_name='Tipo de equivalencia'),
        ),
    ]
