# Generated by Django 5.1.4 on 2026-02-05 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_add_equivalencia_por_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden para mostrar en listas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de ingrediente',
                'verbose_name_plural': 'Tipos de ingrediente',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tipo_ingrediente',
            field=models.ForeignKey(blank=True, help_text='Categoría del ingrediente: lácteos, hortalizas, carnes, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='recipes.tipoingrediente', verbose_name='Tipo de ingrediente'),
        ),
    ]
