# Generated by Django - add tipo (peso/volumen/unidad) to UnidadMedida

from django.db import migrations, models


def asignar_tipo_unidad(apps, schema_editor):
    UnidadMedida = apps.get_model('recipes', 'UnidadMedida')
    peso_keys = ('gramo', 'gr', 'g', 'kilogramo', 'kg', 'libra', 'lb', 'onza', 'oz')
    volumen_keys = ('litro', 'l', 'lt', 'mililitro', 'ml', 'cc', 'cucharada', 'cucharadita', 'taza', 'vaso')
    for u in UnidadMedida.objects.all():
        nombre = (u.nombre or '').strip().lower()
        simbolo = (u.simbolo or '').strip().lower()
        if any(nombre.startswith(k) or k in nombre or simbolo == k for k in volumen_keys):
            u.tipo = 'volumen'
        elif any(nombre.startswith(k) or k in nombre or simbolo == k for k in peso_keys):
            u.tipo = 'peso'
        elif 'unidad' in nombre or simbolo in ('un', 'ud', 'u') or u.nombre and 'unidad' in u.nombre.lower():
            u.tipo = 'unidad'
        else:
            u.tipo = 'peso'
        u.save(update_fields=['tipo'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_add_tipo_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='tipo',
            field=models.CharField(
                choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidad', 'Unidad')],
                default='peso',
                help_text='Peso (g, kg), Volumen (ml, L) o Unidad (piezas). En la receta solo se pueden elegir unidades del mismo tipo que el ingrediente.',
                max_length=10,
                verbose_name='Tipo'
            ),
        ),
        migrations.RunPython(asignar_tipo_unidad, noop),
    ]
