# Generated by Django 6.0.2 on 2026-02-05 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietas', to='plans.plan', verbose_name='Plan asociado')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DietaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de la receta en la dieta (para secuencia de días)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieta_recetas', to='diets.dieta', verbose_name='Dieta')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_dietas', to='recipes.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Receta de Dieta',
                'verbose_name_plural': 'Recetas de Dietas',
                'ordering': ['dieta', 'orden', 'receta'],
                'unique_together': {('dieta', 'receta')},
            },
        ),
        migrations.AddField(
            model_name='dieta',
            name='recetas',
            field=models.ManyToManyField(related_name='dietas', through='diets.DietaReceta', to='recipes.receta', verbose_name='Recetas'),
        ),
    ]
