# Generated by Django 5.1.4 on 2026-02-05 01:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def noop(apps, schema_editor):
    """Sin datos ficticios: los tipos de comida se crean desde la app."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden del momento en el día (1 = desayuno, 2 = media mañana, ...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de comida / Momento',
                'verbose_name_plural': 'Tipos de comida / Momentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='dietareceta',
            options={'ordering': ['dieta', 'tipo_comida', 'orden', 'receta'], 'verbose_name': 'Receta de Dieta', 'verbose_name_plural': 'Recetas de Dietas'},
        ),
        migrations.AlterField(
            model_name='dietareceta',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden de la receta dentro de ese momento (ej. 1º té, 2º galleta, 3º cereal)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden'),
        ),
        migrations.AlterUniqueTogether(
            name='dietareceta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dietareceta',
            name='tipo_comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_recetas', to='diets.tipocomida', verbose_name='Momento / Tipo de comida'),
        ),
        migrations.AlterUniqueTogether(
            name='dietareceta',
            unique_together={('dieta', 'tipo_comida', 'receta')},
        ),
        migrations.RunPython(noop, noop),
    ]
