# Generated by Django 5.1.4 on 2026-02-05 01:31

from django.db import migrations, models


def copiar_plan_a_planes(apps, schema_editor):
    """Copia la relación plan (FK) existente al nuevo M2M planes."""
    Dieta = apps.get_model('diets', 'Dieta')
    for dieta in Dieta.objects.all():
        if dieta.plan_id:
            dieta.planes.add(dieta.plan_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_tipo_comida_required'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='planes',
            field=models.ManyToManyField(blank=True, help_text='Planes para los que puede usarse esta dieta (ej. Calórico, Adelgazamiento)', related_name='dietas', to='plans.plan', verbose_name='Planes asociados'),
        ),
        migrations.RunPython(copiar_plan_a_planes, noop),
        migrations.RemoveField(
            model_name='dieta',
            name='plan',
        ),
    ]
