# Generated by Django 5.1.4 on 2026-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_dieta_planes_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='dietareceta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='dietareceta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
    ]
