# Generated by Django 6.0.2 on 2026-02-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0012_add_entregador_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entregador', models.OneToOneField(help_text='Courier identity in the routes app.', on_delete=django.db.models.deletion.PROTECT, related_name='courier_profile', to='routes.entregador', verbose_name='Entregador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Courier profile',
                'verbose_name_plural': 'Courier profiles',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route', to='routes.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Delivery route',
                'verbose_name_plural': 'Delivery routes',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('sequence', models.PositiveIntegerField(help_text='Order in route (from RutaCliente.orden_entrega).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='deliveries.deliveryroute', verbose_name='Delivery route')),
                ('ruta_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_stop', to='routes.rutacliente', verbose_name='Ruta cliente')),
            ],
            options={
                'verbose_name': 'Delivery stop',
                'verbose_name_plural': 'Delivery stops',
                'ordering': ['delivery_route', 'sequence'],
                'unique_together': {('delivery_route', 'ruta_cliente')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryEventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='deliveries.deliverystop', verbose_name='Stop')),
            ],
            options={
                'verbose_name': 'Delivery event outbox',
                'verbose_name_plural': 'Delivery event outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('version_code', models.PositiveIntegerField(help_text='Current app version code (e.g. 123).')),
                ('min_version_code', models.PositiveIntegerField(help_text='Minimum required version; clients below this should update.')),
                ('apk_url', models.URLField(blank=True, help_text='URL to download APK when update is required.', max_length=500)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile app version',
                'verbose_name_plural': 'Mobile app versions',
                'ordering': ['-version_code'],
                'unique_together': {('platform', 'version_code')},
            },
        ),
        migrations.CreateModel(
            name='CourierLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL, verbose_name='Courier (user)')),
                ('delivery_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='deliveries.deliveryroute', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Courier location ping',
                'verbose_name_plural': 'Courier location pings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier', '-created_at'], name='deliveries__courier_d5c93b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('LOCATION_PING', 'Location ping'), ('ATTEMPT_ARRIVE', 'Attempt arrive'), ('ATTEMPT_DELIVER', 'Attempt deliver'), ('ATTEMPT_FAIL', 'Attempt fail')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_action_events', to=settings.AUTH_USER_MODEL, verbose_name='Courier')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_events', to='deliveries.deliverystop', verbose_name='Stop')),
            ],
            options={
                'verbose_name': 'Delivery action event',
                'verbose_name_plural': 'Delivery action events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier', '-created_at'], name='deliveries__courier_677d18_idx')],
            },
        ),
    ]
